# Generated by Django 5.2.7 on 2025-12-07 07:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BFSTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='患者姓名')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='測試日期')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': 'BFS測試',
                'verbose_name_plural': 'BFS測試列表',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='FaceDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='患者姓名')),
                ('diagnosis_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='診斷日期')),
                ('front_image', models.ImageField(upload_to='face_diagnosis/%Y/%m/%d/front/', verbose_name='正面照片')),
                ('right_image', models.ImageField(upload_to='face_diagnosis/%Y/%m/%d/right/', verbose_name='右側照片')),
                ('left_image', models.ImageField(upload_to='face_diagnosis/%Y/%m/%d/left/', verbose_name='左側照片')),
                ('analysis_report', models.JSONField(blank=True, help_text='存儲面診分析結果的JSON資料', null=True, verbose_name='分析報告')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '面診系統',
                'verbose_name_plural': '面診系統列表',
                'ordering': ['-diagnosis_date'],
            },
        ),
        migrations.CreateModel(
            name='MeridianTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100, verbose_name='患者姓名')),
                ('test_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='測試日期')),
                ('result_pdf', models.FileField(upload_to='meridian_tests/%Y/%m/%d/', verbose_name='測試結果PDF')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '經絡測試',
                'verbose_name_plural': '經絡測試列表',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10, verbose_name='性別')),
                ('blood_type', models.CharField(choices=[('A', 'A型'), ('B', 'B型'), ('AB', 'AB型'), ('O', 'O型')], max_length=3, verbose_name='血型')),
                ('height', models.FloatField(verbose_name='身高(cm)')),
                ('weight', models.FloatField(verbose_name='體重(kg)')),
                ('birth_date', models.DateField(verbose_name='出生日期')),
                ('autoimmune_disease', models.BooleanField(default=False, verbose_name='自體免疫疾病')),
                ('cardiovascular_disease', models.BooleanField(default=False, verbose_name='心血管疾病')),
                ('diabetes', models.BooleanField(default=False, verbose_name='糖尿病')),
                ('chronic_hepatitis', models.BooleanField(default=False, verbose_name='慢性肝炎')),
                ('heart_disease', models.BooleanField(default=False, verbose_name='心臟疾病')),
                ('heart_valve_insufficiency', models.BooleanField(default=False, verbose_name='心臟瓣膜閉鎖不全')),
                ('liver_cirrhosis', models.BooleanField(default=False, verbose_name='肝硬化')),
                ('liver_disease', models.BooleanField(default=False, verbose_name='肝臟病')),
                ('spleen_enlarged', models.BooleanField(default=False, verbose_name='脾臟腫大')),
                ('lung_tuberculosis', models.BooleanField(default=False, verbose_name='肺結核')),
                ('lung_asthma', models.BooleanField(default=False, verbose_name='氣喘')),
                ('lung_inflammation', models.BooleanField(default=False, verbose_name='肺炎')),
                ('lung_covid19', models.BooleanField(default=False, verbose_name='COVID-19')),
                ('kidney_disease', models.BooleanField(default=False, verbose_name='腎臟病')),
                ('kidney_stone', models.BooleanField(default=False, verbose_name='腎結石')),
                ('hemodialysis', models.BooleanField(default=False, verbose_name='洗腎')),
                ('stomach_ulcer', models.BooleanField(default=False, verbose_name='胃炎')),
                ('stomach_reflux', models.BooleanField(default=False, verbose_name='逆流性食道炎')),
                ('intestine_inflammation', models.BooleanField(default=False, verbose_name='發炎性腸道疾病')),
                ('intestine_disease', models.BooleanField(default=False, verbose_name='腸躁症')),
                ('gallbladder_stone', models.BooleanField(default=False, verbose_name='膽結石')),
                ('gallbladder_inflammation', models.BooleanField(default=False, verbose_name='膽囊炎')),
                ('bladder_stone', models.BooleanField(default=False, verbose_name='膀胱結石')),
                ('bladder_inflammation', models.BooleanField(default=False, verbose_name='膀胱炎')),
                ('uterine_inflammation', models.BooleanField(default=False, verbose_name='骨盆腔炎')),
                ('uterine_tumor', models.BooleanField(default=False, verbose_name='子宮肌瘤')),
                ('uterine_syndrome', models.BooleanField(default=False, verbose_name='子宮肌腺症')),
                ('other_chronic', models.TextField(blank=True, verbose_name='其他慢性疾病')),
                ('other_cancer', models.TextField(blank=True, verbose_name='其他癌症')),
                ('other_nerve', models.TextField(blank=True, verbose_name='其他神經疾病')),
                ('other_disease', models.TextField(blank=True, verbose_name='其他疾病')),
                ('allergy_food', models.TextField(blank=True, verbose_name='食物過敏原')),
                ('allergy_drug', models.TextField(blank=True, verbose_name='藥物過敏原')),
                ('allergy_other', models.TextField(blank=True, verbose_name='其他過敏原')),
                ('habit_smoking', models.BooleanField(default=False, verbose_name='吸菸')),
                ('habit_alcohol', models.BooleanField(default=False, verbose_name='喝酒')),
                ('habit_betel', models.BooleanField(default=False, verbose_name='嚼檳榔')),
                ('habit_late_sleep', models.BooleanField(default=False, verbose_name='熬夜')),
                ('habit_other', models.TextField(blank=True, verbose_name='其他不良嗜好')),
                ('sleep_hours', models.FloatField(verbose_name='平均睡眠時間(小時/天)')),
                ('exercise', models.BooleanField(default=False, verbose_name='運動習慣')),
                ('exercise_duration', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)], verbose_name='每次運動時間(分鐘/天)')),
                ('exercise_frequency', models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True, verbose_name='每週運動頻率(幾天/週)')),
                ('menstruation', models.BooleanField(default=False, verbose_name='生理期(女性適用)')),
                ('surgery_history', models.BooleanField(default=False, verbose_name='是否有手術史')),
                ('surgery_1', models.CharField(blank=True, max_length=200, verbose_name='1.手術詳情')),
                ('surgery_2', models.CharField(blank=True, max_length=200, verbose_name='2.手術詳情')),
                ('notes', models.TextField(blank=True, verbose_name='其他備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='填寫日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '問卷',
                'verbose_name_plural': '問卷列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BFSTestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.PositiveIntegerField(verbose_name='檔案編號')),
                ('pdf_file', models.FileField(upload_to='bfs_tests/%Y/%m/%d/', verbose_name='PDF檔案')),
                ('file_description', models.CharField(blank=True, max_length=200, verbose_name='檔案描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳日期')),
                ('bfs_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.bfstest', verbose_name='BFS測試')),
            ],
            options={
                'verbose_name': 'BFS測試檔案',
                'verbose_name_plural': 'BFS測試檔案列表',
                'ordering': ['bfs_test', 'file_number'],
            },
        ),
    ]
