# Generated by Django 5.2.7 on 2025-12-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facediagnosis',
            name='analysis_report',
            field=models.JSONField(blank=True, default=dict, help_text='存儲面診分析結果的JSON資料', verbose_name='分析報告'),
        ),
    ]
