# Generated by Django 5.2.7 on 2026-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_facediagnosis_analysis_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='exercise_frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1天'), (2, '2天'), (3, '3天'), (4, '4天'), (5, '5天'), (6, '6天'), (7, '7天')], help_text='請選擇每週運動 1-7 天', null=True, verbose_name='每週運動頻率(幾天/週)'),
        ),
    ]
